language: clojure
sudo: false
lein: 2.8.1
jdk:
  - oraclejdk9
  - oraclejdk8
script:
  - lein $TEST_OPTIONS test
  - if [ "$TEST_OPTIONS" = "" ]; then ./ext/travisci/secscan.sh src clj "clojure.core/read-string"; fi
env:
  - TEST_OPTIONS=""
  - TEST_OPTIONS="with-profile test-schema-validation"
notifications:
  email: false
